-- 1. List the number of films per category.

select c.name, count(f.title) as number_of_films_per_cat
from category as c
left join film_category as fc
on c.category_id = fc.category_id
left join film as f
on fc.film_id = f.film_id
group by c.name
;
-- 2. Retrieve the store ID, city, and country for each store.
select s.store_id, c.city, country.country
from store as s
left join address as a
on s.address_id = a.address_id
left join city as c
on a.city_id = c.city_id
left join country as country
on c.country_id = country.country_id
;
-- 3.  Calculate the total revenue generated by each store in dollars.
select s.store_id, CONCAT('$', FORMAT(sum(pay.amount),2)) as total_revenue
from store as s
left join staff as staff
on s.store_id = staff.store_id
 left join payment as pay
on staff.staff_id = pay.staff_id
group by s.store_id;

-- 4.  Determine the average running time of films for each category.
select c.name, round(avg(f.length),2) as avg_running_time
from category as c
left join film_category as fc
on c.category_id = fc.category_id
left join film as f
on fc.film_id = f.film_id
group by c.name
;

-- Identify the film categories with the longest average running time.
select c.name, round(avg(f.length),2) as avg_running_time
from category as c
left join film_category as fc
on c.category_id = fc.category_id
left join film as f
on fc.film_id = f.film_id
group by c.name
order by avg_running_time desc
limit  5;


-- Display the top 10 most frequently rented movies in descending order.

select title, count(r.rental_id) as times_rented
from film as f
join inventory as i
on f.film_id = i.film_id
join rental as r
on i.inventory_id = r.inventory_id
group by title
order by times_rented desc;


-- Determine if "Academy Dinosaur" can be rented from Store 1.
select i.store_id, f.title, f.film_id
from film f
join inventory as i
on f.film_id = i.film_id 
where f.title = "Academy Dinosaur";


-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
